# Language
cache: yarn
language: node_js
node_js:
  - "6"
  - "7"
  - "8"
script:
  - yarn
  - yarn build
  - yarn test
after_success: npm run coverage

# Deployment
deploy:
  api_key: $NPM_API_KEY
  email: $NPM_EMAIL_ADDRESS
  on:
    branch: master
    tags: true
  provider: npm

# Integration and Notifications
notifications:
  email:
    on_failure: always
    on_success: never
